# Tratamento de exce√ß√£o
try:
    n = int(input('Digite um n√∫mero inteiro: '))
    print(f"N√∫mero informado: {n}.")
except ValueError:
    print("Ocorreu um erro: o valor informado n√£o √© um n√∫mero inteiro.")
except Exception as e:
    print(f"Ocorreu um erro inesperado: {e}")
finally:
    print("Programa encerrado com sucesso!üòí.")
    